Document: native
Title: Debian native Manual
Author: <insert document author here>
Abstract: This manual describes what native is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/native/native.sgml.gz

Format: postscript
Files: /usr/share/doc/native/native.ps.gz

Format: text
Files: /usr/share/doc/native/native.text.gz

Format: HTML
Index: /usr/share/doc/native/html/index.html
Files: /usr/share/doc/native/html/*.html
